def gv

pipeline {
    agent any
    stages {
        stage("init") {  // this stage prepare/load the groovy functions in script.groovy file here
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage('Checkout Code') {
            steps {
                 echo "cloning repo to jenkins"
                 git 'https://github.com/princewillopah/JENKINS_SHARED_LIBRARY.git'
            }
        }
        stage("build jar") {
            steps {
                script {
                    echo "building jar"
                    gv.buildJar()
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    echo "building image"
                    gv.buildImage()
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    echo "deploying"
                    gv.deployApp()
                }
            }
        }
    }   
}